import {
  AllType,
  BrandType,
  CategoryType,
  ProductType,
} from "./models/product";
import { Gender, User } from "./models/user";
import { v4 as uuidv4 } from "uuid";

export const userlist: User[] = [
  {
    username: "mnh",
    password: "123",
    displayName: "hieu",
    email: "hieumn@ex.com",
    id: uuidv4(),
    address: "123 hieu",
    phonenumber: "123",
    dob: "123",
    gender: Gender.male,
    cart: [],
  },
  {
    username: "hieu",
    password: "123hieu",
    displayName: "hieu",
    id: uuidv4(),
    email: "hieumn2001@ex.com",
    address: "123 hieu",
    phonenumber: "123",
    dob: "123",
    gender: Gender.male,
    cart: [
      {
        id: uuidv4(),
        name: "Batman: Hush MAFEX No.126 Batman (Black Ver.)",
        img: "images/BH.jpeg",
        review: 123,
        price: 94.99,
        rating: 5,
        description:
          "Based on the Batman: Hush story line, the MAFEX Batman action figure toy is fully articulated and stands at 6.30 inches tall. Batman features a poseable wired fabric cape and several accessories including an unmasked Bruce Wayne head sculpt",
        brand: BrandType.mafex,
        category: CategoryType.action_figure,
        available: true,
        all: AllType.new,
        quantity: 1,
      },
    ],
  },
];

export const DefaultProduct: ProductType[] = [
  {
    id: uuidv4(),
    name: "Batman: Hush MAFEX No.126 Batman (Black Ver.)",
    img: "images/BH.jpeg",
    review: 123,
    price: 94.99,
    rating: 5,
    description:
      "Based on the Batman: Hush story line, the MAFEX Batman action figure toy is fully articulated and stands at 6.30 inches tall. Batman features a poseable wired fabric cape and several accessories including an unmasked Bruce Wayne head sculpt",
    brand: BrandType.mafex,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "  Batman: Hush MAFEX No.175 Nightwing",
    img: "images/nw.jpeg",
    review: 123,
    price: 194.99,
    rating: 5,
    description:
      "Based on the Batman: Hush story line, the MAFEX Nightwing figure is a fully articulated figure with his iconic black and blue suit. Nightwing features two head sculptsand interchangeable hands for more display options.",
    brand: BrandType.mafex,
    sale: 19.99,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },
  {
    id: uuidv4(),
    name: "Batman: Hush MAFEX No.170 Huntress",
    img: "images/bw.jpeg",
    review: 123,
    price: 104.99,
    rating: 5,
    description:
      "The MAFEX figure line continues with the Batman: HUSH comic series, this time featuring Huntress! Measuring around 8 inches tall, this articulated Huntress action figure comes with a fabric cape, 2 different facial expressions, and a figure stand.",
    brand: BrandType.mafex,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.pre_order,
  },
  {
    id: uuidv4(),
    name: "Batman: Hush MAFEX No.133 Hush",
    img: "images/hush.jpeg",
    review: 123,
    price: 139.99,
    rating: 5,
    description:
      "Based on the Batman: Hush story line, the MAFEX Hush is a highly detailed, fully articulated figure. Hush features a trench coat and several accessories including 3 interchangeable head sculpts.",
    brand: BrandType.mafex,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Marvel MAFEX No.160 Jean Grey (Comic Ver.)",
    img: "images/jean.jpeg",
    review: 123,
    price: 104.99,
    rating: 5,
    description:
      "Jean Grey, as she appeared in the X-Men comics, leaps into Medicom's MAFEX action figure lineup!  She stands over 6 inches tall, and includes 3 different head sculpts and translucent effects parts. ",
    brand: BrandType.mafex,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Marvel MAFEX No.179 Magneto (Original Comic Ver.)",
    img: "images/magneto.jpeg",
    review: 123,
    price: 139.99,
    rating: 5,
    description:
      "Magneto once again joins Medicom's MAFEX action figure lineup, this time sporting his original comic book look! Magneto is depicted with his short white hair and a stern expression on his face. The figure comes with a variety of effect pieces and accessories to show off Magneto's immense power. ",
    brand: BrandType.mafex,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Kamen Rider S.H.Figuarts Kamen Rider Zi-O (Ohma Form) Exclusive",
    img: "images/zio.jpeg",
    review: 123,
    price: 123.99,
    rating: 5,
    description:
      "From Kamen Rider Zi-O the Movie: Over Quartzer, Kamen Rider Zi-O (Ohma Form) stands about 6 inches tall and contains the high level of articulation S.H.Figuarts is known for.",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.pre_order,
  },
  {
    id: uuidv4(),
    name: "Kamen Rider S.H.Figuarts -Shinkoccho Seihou- Kamen Rider Beast Exclusive",
    img: "images/lion.jpeg",
    review: 123,
    price: 136.99,
    rating: 5,
    description: "123",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: " Kamen Rider S.H.Figuarts Kamen Rider Build Cross-Z Build Form Exclusive",
    img: "images/build.jpeg",
    review: 123,
    price: 134.99,
    rating: 5,
    description:
      "From Kamen Rider Build the Movie: Be the One, Kamen Rider Build Cross-ZBuild Form stands about 6 inches tall and contains the high level of articulation S.H.Figuarts is known for.",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "  Kamen Rider Build S.H.Figuarts Kamen Rider Build (Genius Form) Exclusive",
    img: "images/genius.jpeg",
    review: 123,
    price: 34.99,
    rating: 5,
    description:
      "From Kamen Rider Build comes an S.H.Figuarts figure of the titular character in Genius Form! Measuring almost 6 inches tall, Build comes with alternate hands, the Full Bottle Buster, and Hazard Trigger from episode 45.",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Ultraman Trigger S.H.Figuarts Ultraman Trigger (Multi Type)",
    img: "images/trigger.jpeg",
    review: 123,
    price: 44.99,
    rating: 5,
    description:
      "The Ultraman Trigger series commemorates 55 years since the first Ultraman, and 25 since Ultraman Tiga.It stars an ancient Ultraman who once fought against the darkness ages ago. Now, the titular Ultraman Trigger Multi Type joins S.H.Figuarts! Standing 150mm tall and made of ABS and PVC, the figures development was overseen by Tsuburaya Productions sculpting department LSS, to ensure a faithfully accurate appearance.",
    sale: 19.99,
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },
  {
    id: uuidv4(),
    name: "Ultraman S.H.Figuarts Ultraman Ginga Strium Exclusive",
    img: "images/ginga.jpeg",
    review: 123,
    price: 132.99,
    rating: 5,
    description:
      "Joining the S.H.Figurarts line is Ultraman Ginga Strium based on his appearance in the Ultraman Ginga TV series! Having been produced in close cooperation with the LSS sculpting department of Tsuburaya Productions, the proportions and details of this figure are perfect. This exclusive set includes his iconic Gingal Spark Lance.",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Marvel Legends 20th Anniversary Series Iron Man",
    img: "images/iron.jpeg",
    review: 123,
    price: 34.99,
    rating: 5,
    description:
      "The Armored Avenger takes flight with the 6-inch Series 1 Iron Man figure, inspired by the character’s appearances throughout Marvel Entertainment! This 6-inch scale Series 1 Iron Man figure is inspired by the original 2002 Marvel Legends Iron Man figure, featuring updated articulation, deco, and accessories.",
    brand: BrandType.marvel_legend,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.pre_order,
  },
  {
    id: uuidv4(),
    name: "Marvel Comics 80th Anniversary Marvel Legends Iron Man",
    img: "images/iron2.jpeg",
    review: 123,
    price: 34.99,
    rating: 5,
    description:
      "Marvel Comics 80th anniversary edition action figures: celebrate the 80th anniversary of Marvel Comics with this iron Man 6-inch-scale action figure from the Marvel Legends series.",
    brand: BrandType.marvel_legend,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Avengers: Endgame Marvel Legends The Infinity Saga Iron Man Mark 85 & Thanos Two-Pack",
    img: "images/2p.jpeg",
    review: 123,
    price: 69.99,
    rating: 5,
    description:
      "From figures to vehicles to premium roleplay items, the Marvel Legends Series offers elite character-inspired products for Marvel fans and collectors. The Marvel Legends Iron Man Mark 85 and Thanos figures are packed with details.",
    sale: 39.99,
    brand: BrandType.marvel_legend,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },
  {
    id: uuidv4(),
    name: "Avengers: Infinity War Marvel Legends Loki VS Corvus Glaive Exclusive Two-Pack",
    img: "images/2p3.jpeg",
    review: 123,
    price: 42.99,
    rating: 5,
    description:
      "This 2-pack of Marvel Legends Series figures features Loki and Corvus Glaive 6-inch figures with character-inspired accessories from Avengers: Infinity War",
    sale: 20.99,
    brand: BrandType.marvel_legend,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },
  {
    id: uuidv4(),
    name: "Iron Man Marvel Legends Iron Man Model 70 Armor (Marvel's Controller BAF)",
    img: "images/iron3.jpeg",
    review: 123,
    price: 61.99,
    rating: 5,
    description:
      "Tony Stark resolves to get back to basics, donning a new stripped-down Iron Man armor inspired by his most classic designs. This Iron Man figure features the characters new back-to-basics armor from his recent appearances in Marvel Comics",
    brand: BrandType.marvel_legend,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Iron Man Marvel Legends The Infinity Saga Iron Man Mark III",
    img: "images/iron4.jpeg",
    review: 123,
    price: 28.99,
    rating: 5,
    description:
      "MARVEL ENTERTAINMENT-INSPIRED DESIGN: This Iron Man Mark 3 figure features premium design, detail, and articulation for posing and display in a Marvel collection",
    brand: BrandType.marvel_legend,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "DC Essentials Unkillables Red Hood (DCeased) Figure",
    img: "images/rz.jpeg",
    review: 123,
    price: 29.99,
    rating: 5,
    description:
      "DC ESSENTIALS is a line of 7 action figures based on DC characters with universal appeal, accessible to both longtime collectors and those just starting out, which delivers authentic detail from a company with two decades experience creating high-quality action figures. Based on the popular DC Comics miniseries from 2019, DCeased, this DC Essentials action figure series takes the most popular characters in the line and turns them into zombie like creatures.",
    brand: BrandType.dc_collectibles,

    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "DC Essentials Batgirl (DCeased) Figure",
    img: "images/bz.jpeg",
    review: 123,
    price: 29.99,
    rating: 5,
    description:
      "DC ESSENTIALS is a line of 7 action figures based on DC characters with universal appeal, accessible to both longtime collectors and those just starting out, which delivers authentic detail from a company with two decades' experience creating high-quality action figures. Based on the popular DC Comics miniseries from 2019, DCeased, this DC Essentials action figure series takes the most popular characters in the line and turns them into zombie like creatures.",
    brand: BrandType.dc_collectibles,

    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "DC Essentials Nightwing (DCeased) Figure",
    img: "images/nz.jpeg",
    review: 123,
    price: 29.99,
    rating: 5,
    description:
      "DC ESSENTIALS is a line of 7 action figures based on DC characters with universal appeal, accessible to both longtime collectors and those just starting out, which delivers authentic detail from a company with two decades' experience creating high-quality action figures. Based on the popular DC Comics miniseries from 2019, DCeased, this DC Essentials action figure series takes the most popular characters in the line and turns them into zombie like creatures",
    brand: BrandType.dc_collectibles,

    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "DC Essentials The Joker (DCeased) Figure",
    img: "images/jz.jpeg",
    review: 123,
    price: 29.99,
    rating: 5,
    description:
      "From the popular DC Comics 2019 miniseries DCeased, The Joker has been transformed into a zombie like creature for this release of DC Essentials.",
    brand: BrandType.dc_collectibles,

    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "DC Essentials Superman (DCeased) Figure",
    img: "images/sz.jpeg",
    review: 123,
    price: 29.99,
    rating: 5,
    description:
      "From the popular DC Comics 2019 miniseries DCeased, Superman has been transformed into a zombie like creature for this release of DC Essentials.",
    brand: BrandType.dc_collectibles,
    sale: 19.99,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },
  {
    id: uuidv4(),
    name: "DC Essentials The Batman (DCeased) Figure",
    img: "images/batz.jpeg",
    review: 123,
    price: 29.99,
    rating: 5,
    description:
      "From the popular DC Comics 2019 miniseries DCeased, Batman has been transformed into a zombie like creature for this release of DC Essentials.",
    brand: BrandType.dc_collectibles,
    sale: 19.99,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },
  {
    id: uuidv4(),
    name: " Marvel Legends Series Loki Agent of Asgard 6-inch Retro",
    img: "images/loki.jpeg",
    review: 123,
    price: 24.99,
    rating: 5,
    description:
      "This Loki figure features premium comics-inspired design, detail, and articulation for posing and display in your Marvel collection!",
    brand: BrandType.marvel_legend,
    sale: 22.0,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },

  {
    id: uuidv4(),
    name: " WWE Randy Orton Elite Collection Action Figure, Series # 90",
    img: "images/randy.jpeg",
    review: 123,
    price: 21.0,
    rating: 5,
    description:
      "This WWE Randy Orton figure has deluxe articulation, detailed character expression, authentic ring attire, and iconic accessories. Get all the WWE Elite Collection figures and let the battles begin!",
    brand: BrandType.mattel,
    sale: 15.0,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },
  {
    id: uuidv4(),
    name: "McFarlane Multiverse The Batman from Batman Movie Deluxe Figure",
    img: "images/batman.jpeg",
    review: 123,
    price: 35.0,
    rating: 5,
    description:
      "Incredibly detailed 12 scale statue based on the DC Multiverse.Batman is fully colored to resemble the suit in the upcoming movie The Batman.Comes with a brick rooftop base and a Batarang.Included collectible art card with figure photography on the front, and character biography on the back",
    brand: BrandType.mcfarlane,
    category: CategoryType.statue,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "WWE Ultimate Edition Brock Lesnar",
    img: "images/brock.jpeg",
    review: 123,
    price: 36.99,
    rating: 5,
    description:
      "Kick your WWE collection up a notch with this WWE Ultimate Edition Brock Lesnar action figure! This Ultimate action figure features authentic ring gear and accessories.",
    brand: BrandType.mattel,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "WWE Ultimate Edition The Rock Figure",
    img: "images/rock.jpeg",
    review: 123,
    price: 36.99,
    rating: 5,
    description:
      "Kick your WWE collection up a notch with this WWE Ultimate Edition The Rock action figure! This Ultimate action figure features authentic ring gear and accessories.",
    brand: BrandType.mattel,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "WWE Ultimate Edition John Cena Figure",
    img: "images/cena.jpeg",
    review: 123,
    price: 36.99,
    rating: 5,
    description:
      "Kick your WWE collection up a notch with this WWE Ultimate Edition John Cena action figure! This Ultimate action figure features authentic ring gear and accessories.",
    brand: BrandType.mattel,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.pre_order,
  },
  {
    id: uuidv4(),
    name: "DC Comics Super Man and Lois Lane 1/6 Scale Diorama",
    img: "images/sups.jpeg",
    review: 123,
    price: 666.99,
    rating: 5,
    description:
      "From Iron Studios comes this 1/6 scale diorama of Superman and Lois. This diorama features the characters in an embrace, as they float effortlessly above The Daily Planet and the skyline of Metropolis. Standing over 22 inches, this diorama will stand out in your collection!",
    brand: BrandType.figuart,
    category: CategoryType.statue,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Darkstalkers Felicia (Black Ver.) Limited Edition 1/4 Scale Statue",
    img: "images/dark.jpeg",
    review: 123,
    price: 849.99,
    rating: 5,
    description:
      "HMO’s second statue from the world of Capcom’s Darkstalkers series is the loving, caring, warm-hearted cutie, Felicia!In this limited edition premium 1/4 scale statue, Felicia has been reimagined with all her cat friends under HMO’s master-level paint applications; their artisans will awe fans once again with their innovative techniques.",
    brand: BrandType.figuart,
    category: CategoryType.statue,
    available: true,
    all: AllType.pre_order,
  },
  {
    id: uuidv4(),
    name: "DC Rebirth Premium Collectibles Catwoman Limited Edition Statue",
    img: "images/cat.jpeg",
    review: 123,
    price: 499.99,
    rating: 5,
    description:
      "From the DC Rebirth series, XM Studios is excited to present Catwoman into the DC Premium Collectibles statue line. At 1/6 scale, Catwoman has been immortalized atop a Gotham City Gargoyle with whip in hand and feline companion at her side.",
    brand: BrandType.figuart,
    category: CategoryType.statue,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Vampirella 1/3 Scale Statue",
    img: "images/vamp.jpeg",
    review: 123,
    price: 919.99,
    rating: 5,
    description:
      "Premium Collectibles Studio presents the Vampirella 1:3 Scale Statue, a scintillating supernatural statue celebrating this iconic Dynamite Entertainment heroine.",
    brand: BrandType.figuart,
    category: CategoryType.statue,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Journey to the West Monkey King (Blue) Limited Edition Statue",
    img: "images/tnk.jpeg",
    review: 123,
    price: 139.99,
    rating: 5,
    description:
      "From the classic Chinese novel Journey to the West, Infinity Studio has created a beautiful rendition of the main character, Monkey King. At a height of over 20 inches the Monkey King stands upon a rock themed base and includes an interchangeable head and arm.",
    brand: BrandType.figuart,
    category: CategoryType.statue,
    available: true,
    all: AllType.new,
  },

  {
    id: uuidv4(),
    name: " The Batman 1/10 Art Scale Limited Edition Statue",
    img: "images/Pbat.jpeg",
    review: 123,
    price: 174.99,
    rating: 5,
    description:
      "From the new DC Comics movie The Batman, comes a new Art Scale statue of the titular hero! Batman is presented in 1/10 scale and features the great detail that fans have come to expect from Iron Studios.",
    brand: BrandType.figuart,
    category: CategoryType.statue,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Dragon Ball Super S.H.Figuarts Super Saiyan God Super Saiyan Gogeta",
    img: "images/Pgoku.jpeg",
    review: 123,
    price: 59.99,
    rating: 5,
    description:
      "From the hit Dragon Ball Z: Fusion Reborn 1995 theatrical anime this figure features the fusion of Gokou and Vegeta, as the ultimate Super Saiyan Gogeta! And now featuring his never-before-seen God Super Saiyan form appearance from the film Dragon Ball Super: Broly! This figure has it all, from the nostalgia factor of a beloved character to an all-new appearance from this film! ",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Dragon Ball Super S.H.Figuarts Super Saiyan Broly (Full Power) ",
    img: "images/Pbroly.jpeg",
    review: 123,
    price: 83.99,
    rating: 5,
    description:
      "From his first appearance in Dragon Ball Z: Broly – The Legendary Super Saiyan,followed by his reign of terror through Dragon Ball Z: Broly – Second Coming and Dragon Ball Z: Bio-Broly! The enemy of Goku and friends is the latest addition to the S.H.Figuarts lineup! Featuring an all new Broly, standing at a huge 8.6 inches tall, this is one super-sized figure fans won't want to miss!",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Spider-Man: No Way Home S.H.Figuarts The Friendly Neighborhood Spider-Man",
    img: "images/s2.jpeg",
    review: 123,
    price: 94.99,
    rating: 5,
    description:
      "Peter 2, making a surprise comeback after 20 years in Spider-Man: No Way Home, joins S.H.Figuarts!",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "The Amazing Spider-Man 2 S.H.Figuarts Spider-Man ",
    img: "images/s3.png",
    review: 123,
    price: 94.99,
    rating: 5,
    description:
      "This figure faithfully replicates his Spider-suit's fine detail, with translucent parts used for the eyes to bring the figure to life for dynamic action scenes. Re-create the drama of The Amazing Spider-Man 2 on your desktop or display shelf!",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "SNaruto: Shippuden S.H.Figuarts Sasuke Uchiha (He Who Bears All Hatred)",
    img: "images/sasuke.jpeg",
    review: 123,
    price: 59.99,
    rating: 5,
    description:
      "From the Naruto: Shippuden anime, Uchiha Sasuke joins the S.H.Figuarts line! Standing almost 6 inches tall, Uchiha is highly articulated and includes several hand options as well as his signature sword. ",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: "Naruto: Shippuden S.H.Figuarts Naruto Uzumaki (The Jinchuuriki Entrusted with Hope) ",
    img: "images/naruto.jpeg",
    review: 123,
    price: 34.99,
    rating: 5,
    description:
      "From the Naruto: Shippuden anime, Naruto joins the S.H.Figuarts again! Standing over 5.5 inches tall, Naruto is highly articulated and includes several hand options as well as a Kunai and a Rasengan effect. ",
    brand: BrandType.shf,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },

  {
    id: uuidv4(),
    name: " WWE Ultimate Edition 14 Roman Reigns",
    img: "images/roman.jpeg",
    review: 123,
    price: 36.99,
    rating: 5,
    description:
      "Kick your WWE collection up a notch with this WWE Ultimate Edition Roman Reigns action figure! This Ultimate action figure features authentic ring gear and accessories.",
    brand: BrandType.mattel,
    sale: 15.0,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },

  {
    id: uuidv4(),
    name: "WWE Ultimate Edition 13 Hulk Hogan",
    img: "images/Phogan.jpeg",
    review: 123,
    price: 36.99,
    rating: 5,
    description:
      "Kick your WWE collection up a notch with this WWE Ultimate Edition Hulk Hogan action figure! This Ultimate action figure features authentic ring gear and accessories.",
    brand: BrandType.mattel,
    sale: 15.0,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },
  {
    id: uuidv4(),
    name: " Justice League (2021) DC Multiverse Superman Action Figure",
    img: "images/sup.jpeg",
    review: 123,
    price: 19.99,
    rating: 5,
    description:
      "Once the world’s most powerful and iconic Super Hero, Superman personified a higher calling to truth and justice and a deep respect for all humanity. The absence of this fallen idol, whose sacrifice stunned the world, inspires the formation of the Justice League.",
    brand: BrandType.mcfarlane,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },

  {
    id: uuidv4(),
    name: "Justice League (2021) DC Multiverse Aquaman Action Figure",
    img: "images/aquaman.jpeg",
    review: 123,
    price: 19.99,
    rating: 5,
    description:
      "Half human, half Atlantean, Arthur Curry is an outsider who does not feel at home on the Earth’s surface or at sea.  That is, until the world is threatened and he joins Batman’s newly assembled team of heroes.",
    brand: BrandType.mcfarlane,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.new,
  },
  {
    id: uuidv4(),
    name: " Justice League (2021) DC Multiverse Darkseid Mega Action Figure",
    img: "images/darkseid.jpeg",
    review: 123,
    price: 49.99,
    rating: 5,
    description:
      "These 7-inch scale figures are designed with McFarlane's signature Ultra Articulation with up to 22 moving parts for full range and posing. Each DC Multiverse figure includes a collectible art card with artwork on the front and character biographies on the back.",
    brand: BrandType.mcfarlane,
    sale: 15.0,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },

  {
    id: uuidv4(),
    name: "Justice League (2021) DC Multiverse The Flash Action Figure",
    img: "images/flash.jpeg",
    review: 123,
    price: 19.99,
    rating: 5,
    description:
      "Barry Allen is an excessively energetic student attending Central City College, where he studies criminal justice with the hope of one day freeing his incarcerated father.  More than eager to team up with crime fighting icon Batman, Barry’s remarkably quick wit is surpassed only by his ability to move at hyper-speed.",

    brand: BrandType.mcfarlane,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.pre_order,
  },

  {
    id: uuidv4(),
    name: "Batman: The Dark Knight Returns DC Multiverse Superman vs. Armored Batman Two-Pack",
    img: "images/bvs.jpeg",
    review: 123,
    price: 49.99,
    rating: 5,
    description:
      "This 7-inch scale figure two-pack was designed with McFarlane's signature Ultra Articulation with up to 22 moving parts for full range and posing.",
    sale: 15.0,
    brand: BrandType.mcfarlane,
    category: CategoryType.action_figure,
    available: true,
    all: AllType.sale,
  },
];
