import { BrandType, CategoryType, ProductType } from "./models/product";
import { Gender, User } from "./models/user";
import { v4 as uuidv4, v4 } from "uuid";

export const userlist: User[] = [
  {
    username: "hieu2",
    password: "123hieu2",
    name: "hieu",
    id: "123",
    address: "123 hieu",
    phone: "123",
    birthday: "123",
    gender: Gender.male,
  },
  {
    username: "hieu",
    password: "123hieu",
    name: "hieu",
    id: "123",
    address: "123 hieu",
    phone: "123",
    birthday: "123",
    gender: Gender.male,
  },
];

export const DefaultProduct: ProductType[] = [
  {
    id: v4(),
    name: "Batman: Hush MAFEX No.126 Batman (Black Ver.)",
    img: "images/BH.jpeg",
    review: 123,
    price: 94.99,
    rating: 1,
    description: "123",
    brand: BrandType.dc_collectibles,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "  Batman: Hush MAFEX No.175 Nightwing",
    img: "images/nw.jpeg",
    review: 123,
    price: 194.99,
    rating: 1,
    description: "123",
    brand: BrandType.dc_collectibles,
    sale: 123,
    category: CategoryType.statue,
    available: true,
  },
  {
    id: v4(),
    name: "Batman: Hush MAFEX No.170 Huntress",
    img: "images/bw.jpeg",
    review: 123,
    price: 104.99,
    rating: 1,
    description: "123",
    brand: BrandType.dc_collectibles,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "Batman: Hush MAFEX No.133 Hush",
    img: "images/hush.jpeg",
    review: 123,
    price: 139.99,
    rating: 1,
    description: "123",
    brand: BrandType.dc_collectibles,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: " Kamen Rider S.H.Figuarts Kamen Rider Build Cross-ZBuild Form Exclusive",
    img: "images/build.jpeg",
    review: 123,
    price: 134.99,
    rating: 1,
    description: "123",
    brand: BrandType.shf,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "  Kamen Rider Build S.H.Figuarts Kamen Rider Build (Genius Form) Exclusive",
    img: "images/genius.jpeg",
    review: 123,
    price: 34.99,
    rating: 1,
    description: "123",
    brand: BrandType.shf,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "Marvel Legends 20th Anniversary Series Iron Man",
    img: "images/iron.jpeg",
    review: 123,
    price: 34.99,
    rating: 1,
    description: "123",
    brand: BrandType.marvel_legend,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "Marvel Comics 80th Anniversary Marvel Legends Iron Man",
    img: "images/iron2.jpeg",
    review: 123,
    price: 34.99,
    rating: 1,
    description: "123",
    brand: BrandType.marvel_legend,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "WWE Ultimate Edition Brock Lesnar",
    img: "images/brock.jpeg",
    review: 123,
    price: 36.99,
    rating: 1,
    description: "123",
    brand: BrandType.mattel,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "WWE Ultimate Edition The Rock Figure",
    img: "images/rock.jpeg",
    review: 123,
    price: 36.99,
    rating: 1,
    description: "123",
    brand: BrandType.mattel,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "Ultraman Trigger S.H.Figuarts Ultraman Trigger (Multi Type)",
    img: "images/trigger.jpeg",
    review: 123,
    price: 44.99,
    rating: 1,
    description: "123",
    brand: BrandType.shf,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "Ultraman S.H.Figuarts Ultraman Ginga Strium Exclusive",
    img: "images/ginga.jpeg",
    review: 123,
    price: 132.99,
    rating: 1,
    description: "123",
    brand: BrandType.shf,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "DC Essentials Unkillables Red Hood (DCeased) Figure",
    img: "images/rz.jpeg",
    review: 123,
    price: 29.99,
    rating: 1,
    description: "123",
    brand: BrandType.dc_collectibles,
    sale: 19.99,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "DC Essentials Batgirl (DCeased) Figure",
    img: "images/bz.jpeg",
    review: 123,
    price: 29.99,
    rating: 1,
    description: "123",
    brand: BrandType.dc_collectibles,
    sale: 19.99,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "DC Essentials Nightwing (DCeased) Figure",
    img: "images/nz.jpeg",
    review: 123,
    price: 29.99,
    rating: 1,
    description: "123",
    brand: BrandType.dc_collectibles,
    sale: 19.99,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "DC Essentials The Joker (DCeased) Figure",
    img: "images/jz.jpeg",
    review: 123,
    price: 29.99,
    rating: 1,
    description: "123",
    brand: BrandType.dc_collectibles,
    sale: 19.99,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: " Marvel Legends Series Loki Agent of Asgard 6-inch Retro",
    img: "images/loki.jpeg",
    review: 123,
    price: 24.99,
    rating: 1,
    description: "123",
    brand: BrandType.marvel_legend,
    sale: 22.0,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: " WWE Randy Orton Elite Collection Action Figure, Series # 90",
    img: "images/randy.jpeg",
    review: 123,
    price: 21.0,
    rating: 1,
    description: "123",
    brand: BrandType.mattel,
    sale: 15.0,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: "McFarlane Multiverse The Batman from Batman Movie Deluxe Figure",
    img: "images/batman.jpeg",
    review: 123,
    price: 35.0,
    rating: 1,
    description: "123",
    brand: BrandType.mcfarlane,
    sale: 30.0,
    category: CategoryType.statue,
    available: true,
  },
  {
    id: v4(),
    name: "Dragon Ball Super S.H.Figuarts Super Saiyan God Super Saiyan Gogeta",
    img: "images/Pgoku.jpeg",
    review: 123,
    price: 59.99,
    rating: 1,
    description: "123",
    brand: BrandType.shf,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
  {
    id: v4(),
    name: " The Batman 1/10 Art Scale Limited Edition Statue",
    img: "images/Pbat.jpeg",
    review: 123,
    price: 174.99,
    rating: 1,
    description: "123",
    brand: BrandType.shf,
    sale: 123,
    category: CategoryType.statue,
    available: true,
  },
  {
    id: v4(),
    name: "Dragon Ball Super S.H.Figuarts Super Saiyan Broly (Full Power) ",
    img: "images/Pbroly.jpeg",
    review: 123,
    price: 83.99,
    rating: 1,
    description: "123",
    brand: BrandType.shf,
    sale: 123,
    category: CategoryType.action_figure,
    available: true,
  },
];
